# Generated by Django 5.2.8 on 2025-11-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cp_pdf',
            field=models.FileField(blank=True, null=True, upload_to='cv_pdfs/'),
        ),
    ]
