# Generated by Django 5.2.8 on 2025-11-14 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_cp_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='cp_pdf',
            new_name='cv_pdf',
        ),
    ]
