# Generated by Django 5.2.8 on 2025-11-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_rename_cp_pdf_userprofile_cv_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pdf_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
