# Generated by Django 5.2.8 on 2025-11-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_userprofile_pdf_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pdf_text',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
