# Generated by Django 5.2.8 on 2025-11-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_userprofile_pdf_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='career_interests',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
