# Generated by Django 5.2.8 on 2025-11-28 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_userprofile_career_interests_and_more'),
    ]

    operations = [
    ]
