# Generated by Django 5.2.8 on 2025-11-12 18:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
                ('location', models.CharField(default='Remote', max_length=100)),
                ('required_skills', models.JSONField(default=list)),
                ('experience_level', models.CharField(choices=[('Fresher', 'Fresher'), ('Junior', 'Junior'), ('Mid', 'Mid')], max_length=20)),
                ('job_type', models.CharField(choices=[('Internship', 'Internship'), ('Part-time', 'Part-time'), ('Full-time', 'Full-time'), ('Freelance', 'Freelance')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
