# Generated by Django 5.2.8 on 2025-11-13 07:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('related_skills', models.JSONField()),
                ('cost', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], max_length=10)),
            ],
        ),
    ]
